next_class_briefing:
  description: >
    The user asked: "{user_question}"

    Based on this specific question, analyze the MIT AI Studio Fall 2025 schedule to provide
    the information they need about the next upcoming class. Read the schedule.csv file at
    {schedule_path} to find information about classes, and use {current_date} as today's date.

    IMPORTANT: Tailor your response to answer their specific question. If they only want the
    date, just provide the date. If they want the topic, just the topic. If they ask for
    comprehensive details, provide full information. Always respect the user's specific request.
  expected_output: >
    A response that directly and precisely answers the user's question: "{user_question}"

    Use the schedule data to provide accurate information. Match the level of detail to what
    the user requested - concise if they want specific info, comprehensive if they want full details.
  agent: schedule_navigator

topic_primer:
  description: >
    The user asked: "{user_question}"

    Research the topic "{topic}" related to the MIT AI Studio course. Tailor your research
    and response to address the user's specific question.

    IMPORTANT: Keep your answer CONCISE (2-3 sentences) unless the user explicitly asks for
    detailed, comprehensive, or in-depth information. Focus on the key insight that answers
    their question directly. If they ask about specific aspects (current trends, key concepts,
    applications), focus on those briefly.

    Use web search and research tools to gather current, accurate information.
  expected_output: >
    A CONCISE response (2-3 sentences) that directly answers: "{user_question}"

    Provide a brief, focused answer about {topic}. Only expand to detailed explanations if
    the user explicitly requested comprehensive, detailed, or in-depth information.
  agent: topic_researcher

weekly_preparation:
  description: >
    The user asked: "{user_question}"

    Create a preparation plan based on what the user needs. Read the schedule at {schedule_path}
    and user preferences at {preferences_path}. Starting from {current_date}, tailor your plan
    to their specific request.

    If they want a full weekly plan, provide detailed daily breakdown. If they only want to know
    about upcoming classes, focus on that. If they ask about specific homework or topics, address
    those specifically. Personalize based on their learning preferences.
  expected_output: >
    A response that directly answers: "{user_question}"

    Provide a preparation plan with appropriate detail level based on user's request. May include
    daily tasks, class preparation, homework reminders, study allocations, or topic previews -
    depending on what was specifically requested.
  agent: study_coordinator

assignment_tracker:
  description: >
    The user asked: "{user_question}"

    Read the MIT AI Studio schedule from {schedule_path} and track assignments for the {track} Track.
    Tailor your response to their specific question. Starting from {current_date}, if they want all
    assignments, list everything. If they only want upcoming ones, focus on those. If they ask about
    a specific assignment or deadline, address that precisely.

    Parse the CSV homework columns carefully and organize based on what the user needs.
  expected_output: >
    A response that directly answers: "{user_question}"

    Provide assignment information for {track} Track with appropriate detail. May include assignment
    lists, due dates, status, descriptions, or progress summary - depending on the user's specific request.
  agent: schedule_navigator